### ISSUE TITLE
[Idea] Create GitHub Releases for new versions

### ISSUE THREAD

**Issue by CoreMoni** [nginxinc/docker-nginx-unprivileged#105]
As we always want to use the newest versions of the tools we are using we used the feature of GitHub to watch new Releases. 

Going to Watch --> Custom --> Check the checkbox of Releases --> Apply

This GitHub feature will only work if there are any Relaseses. Is it many also possible for nginx to create GitHub Releases in the future. 
This will help us and I hope more companies very much.

**Comment by alessfg** [comment]
This seems like a good idea. I'll start creating a new release whenever a new version of NGINX comes out 😄

**Comment by alessfg** [comment]
As of today, new releases will be appropriately created and tagged 😄
