### ISSUE TITLE
Can't modify files in /etc/nginx/* when using this image

### ISSUE THREAD

**Issue by admiralobvious** [nginxinc/docker-nginx-unprivileged#11]
Since the image properly uses the `nginx` user now, you cannot modify anything in the `/etc/nginx/` folder since it's owned by `root:root` and has `755` permissions.

Maybe the folder should be `chmod`'d to be owned by the `nginx` user now? As a workaround I just do this in my Dockerfile:
```
USER root
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx_conf/nginx.conf /etc/nginx/
COPY nginx_conf/vhost.conf /etc/nginx/conf.d/
USER nginx
```

**Comment by admiralobvious** [comment]
I am doing a multistage build that builds a web app in a `node` container and copies the resulting files in the `nginx-unprivileged` container in `/usr/share/nginx/html/` and then I copy the config files that are in my repo in `nginx_conf/` as I showed in my first post.

Finally this is built using the following command locally/on CI machines:
`docker build --build-arg ENV_NAME=<env> -t <my-tag> .`

I didn't try to use volumes as I prefer to just have all the files built into my container so I can just run the container and everything just works. Makes it easier to use in Kubernetes manifests as well.

The full Dockerfile:
```
ARG NODE_VERSION=10.14.0-alpine
ARG NGINX_VERSION=1.15.5-alpine
FROM node:${NODE_VERSION} as builder

ARG ENV_NAME=local
ENV ENV_NAME ${ENV_NAME}

WORKDIR /build
COPY package.json yarn.lock /build/
RUN yarn
COPY . /build/
RUN yarn build:${ENV_NAME}

FROM nginxinc/nginx-unprivileged:${NGINX_VERSION}
COPY --from=builder /build/appcache /usr/share/nginx/html/appcache/
COPY --from=builder /build/appcache /usr/share/nginx/html/dist/appcache/
COPY --from=builder /build/dist /usr/share/nginx/html/dist/
COPY --from=builder /build/index.html /usr/share/nginx/html
COPY --from=builder /build/static/assets /usr/share/nginx/html/assets/
COPY --from=builder /build/static/locales /usr/share/nginx/html/locales/
COPY --from=builder /build/static/manifest.json /usr/share/nginx/html

USER root
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx_conf/nginx.conf /etc/nginx/
COPY nginx_conf/klik.co.conf /etc/nginx/conf.d/
USER nginx

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
```

**Comment by stephenmoloney** [comment]
If you want to use your own image that's fine. The user should be `USER 1001` on kubernetes as kubernetes takes numerical uids for users.

The typical way to do what you want is to mount a configmap volume in kuberenetes and it should work.

**Comment by admiralobvious** [comment]
Right, I know about configmaps, but for custom apps (that change often) that have a Dockerfile, I'd rather just have all the configs builtin the image so I can have the source code + Dockerfile + configs in one repo. I personally keep all my Kubernetes manifests in their own repo (makes it easy to have an overview of your infrastructure and spinning a complete one) so not having to go edit the manifests there is a plus.

I am fine with the workaround I am currently using. Thank you for reply though, that way all bases are covered if someone finds this thread.
