### ISSUE TITLE
breaking change with new builds

### ISSUE THREAD

**Issue by alesbrelih** [nginxinc/docker-nginx-unprivileged#122]
### Describe the bug

I've noticed that image tags were overwritten in last few days/hours from the main branch content. This broke our configuration due to the docker user change from UID to nginx.

Docker history of the new tag that got overwritten:
```
docker history docker.io/nginxinc/nginx-unprivileged:1.23.2-alpine-slim
IMAGE          CREATED       CREATED BY                                      SIZE      COMMENT
e38f12a31b95   6 hours ago   CMD ["nginx" "-g" "daemon off;"]                0B        buildkit.dockerfile.v0
<missing>      6 hours ago   USER nginx                                      0B        buildkit.dockerfile.v0
<missing>      6 hours ago   STOPSIGNAL SIGQUIT                              0B        buildkit.dockerfile.v0
<missing>      6 hours ago   EXPOSE map[8080/tcp:{}]                         0B        buildkit.dockerfile.v0
<missing>      6 hours ago   ENTRYPOINT ["/docker-entrypoint.sh"]            0B        buildkit.dockerfile.v0
<missing>      6 hours ago   COPY 30-tune-worker-processes.sh /docker-ent…   4.62kB    buildkit.dockerfile.v0
<missing>      6 hours ago   COPY 20-envsubst-on-templates.sh /docker-ent…   1.26kB    buildkit.dockerfile.v0
<missing>      6 hours ago   COPY 10-listen-on-ipv6-by-default.sh /docker…   2.13kB    buildkit.dockerfile.v0
<missing>      6 hours ago   COPY docker-entrypoint.sh / # buildkit          1.62kB    buildkit.dockerfile.v0
<missing>      6 hours ago   RUN |2 UID=101 GID=101 /bin/sh -c sed -i 's,…   10.7kB    buildkit.dockerfile.v0
<missing>      6 hours ago   RUN |2 UID=101 GID=101 /bin/sh -c set -x    …   4.56MB    buildkit.dockerfile.v0
<missing>      6 hours ago   ARG GID=101                                     0B        buildkit.dockerfile.v0
<missing>      6 hours ago   ARG UID=101                                     0B        buildkit.dockerfile.v0
<missing>      6 hours ago   ENV PKG_RELEASE=1                               0B        buildkit.dockerfile.v0
<missing>      6 hours ago   ENV NGINX_VERSION=1.23.2                        0B        buildkit.dockerfile.v0
<missing>      6 hours ago   LABEL maintainer=NGINX Docker Maintainers <d…   0B        buildkit.dockerfile.v0
<missing>      3 weeks ago   /bin/sh -c #(nop)  CMD ["/bin/sh"]              0B        
<missing>      3 weeks ago   /bin/sh -c #(nop) ADD file:685b5edadf1d5bf0a…   7.46MB
```

### To reproduce

Pull docker image using:
```
docker pull nginxinc/nginx-unprivileged:1.23.2-alpine-slim
```

Inspect content:
```
docker history docker.io/nginxinc/nginx-unprivileged:1.23.2-alpine-slim
```

### Expected behavior

Dockerfile content should match to the one of the [1.23.2 tag](https://github.com/nginxinc/docker-nginx-unprivileged/blob/1.23.2/mainline/alpine-slim/Dockerfile).

### Your environment

```
docker --version
Docker version 20.10.21, build baeda1f
```

**Comment by alessfg** [comment]
The NGINX user UID should still be 101 -- does your environment depend on the UID being explicitly set as the UID instead of the username? Trying to understand a bit more if this is a big enough breaking change to revert it until 1.23.3 comes out in the next day or two.

**Comment by alesbrelih** [comment]
The NGINX user UID is still 101 indeed. This isn't problematic.

The breaking change was introduced for the Kubernetes only.

If you use the **runAsNonRoot: true** in the pod security context it requires for the container user to be numeric. This was working with the previous version of this image due to the fact that the user was set to UID instead of name.

Once this change was introduced, the pod deployment started to fail with this error:

```
Error: container has runAsNonRoot and image has non-numeric user (nginx), cannot verify user is non-root...
```

If the plan is to move away from the 101 to nginx user in the next versions of this docker image, we will update security context to include **runAsUser:101** directive which will solve the problem. We didn't want to set it beforehand because we didn't want to 'hardcode' user id in case it would change in the next versions.

**Comment by alesbrelih** [comment]
Thank you very much for your fast response and help 🙇
