### ISSUE TITLE
"/tmp/proxy_temp" failed (13: Permission denied) Error on Startup for arm64 based device

### ISSUE THREAD

**Issue by m-picc** [nginxinc/docker-nginx-unprivileged#126]
### Describe the bug

The `nginxinc/nginx-unprivileged:alpine-slim` image fails to startup on a arm64 based OS while the  `nginxinc/nginx-unprivileged:latest` image runs successfully

### To reproduce

1. On an arm64 based device, run `docker run -it nginxinc/nginx-unprivileged:alpine-slim`
2. the following output occurs:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/12/28 17:34:38 [emerg] 1#1: mkdir() "/tmp/proxy_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/tmp/proxy_temp" failed (13: Permission denied)
```

### Expected behavior

I expected the nginx process to startup successfully just as the normal `nginxinc/nginx-unprivileged:latest` image does on an arm64 based device.

### Your environment

- Version of Docker: `Docker version v19.03.15-ce, build 99e3ed8919`
- Version of the NGINX Unprivileged Docker image: `nginxinc/nginx-unprivileged:alpine-slim`
- Target deployment environment/platform: arm64

**Comment by alessfg** [comment]
Heya! I can't seem to replicate the issue on my end. Does the normal `alpine` image work as expected?

**Comment by alessfg** [comment]
Closing this for the time being since I haven't heard back. If you require further help/assistance, feel free to reopen it!

**Comment by js-lowes** [comment]
Ran into the same problem:

System Info: Mac M1

```
$ docker run -it --rm --platform linux/amd64 --entrypoint /bin/sh nginxinc/nginx-unprivileged:1.23-alpine                
Unable to find image 'nginxinc/nginx-unprivileged:1.23-alpine' locally
1.23-alpine: Pulling from nginxinc/nginx-unprivileged
63b65145d645: Already exists 
32c8a27d0c61: Already exists 
e97da5156b50: Already exists 
78f18f372d45: Already exists 
67b050d8a303: Already exists 
35f41fee570a: Already exists 
361c5fde98e1: Already exists 
fd5bdb92e032: Already exists 
Digest: sha256:7c3abf62751d54d26a5a43b611c0a62eb7a1ad371bca3634879fa5f87ee06076
Status: Downloaded newer image for nginxinc/nginx-unprivileged:1.23-alpine
/ $ mkdir /tmp/temp_proxy
mkdir: can't create directory '/tmp/temp_proxy': No space left on device
/ $ 
```

**Comment by alessfg** [comment]
Did you check that you do have space left in your Docker storage partition? It runs fine on my end:
```bash
$ docker run -it --rm --platform linux/amd64 --entrypoint /bin/sh nginxinc/nginx-unprivileged:1.23-alpine
Unable to find image 'nginxinc/nginx-unprivileged:1.23-alpine' locally
1.23-alpine: Pulling from nginxinc/nginx-unprivileged
63b65145d645: Pull complete
32c8a27d0c61: Pull complete
e97da5156b50: Pull complete
78f18f372d45: Pull complete
67b050d8a303: Pull complete
35f41fee570a: Pull complete
361c5fde98e1: Pull complete
fd5bdb92e032: Pull complete
Digest: sha256:7c3abf62751d54d26a5a43b611c0a62eb7a1ad371bca3634879fa5f87ee06076
Status: Downloaded newer image for nginxinc/nginx-unprivileged:1.23-alpine
WARNING: image with reference nginxinc/nginx-unprivileged was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64
/ $ mkdir /tmp/temp_proxy
/ $ 
```

**Comment by js-lowes** [comment]
I am pretty sure its not a space issue, but something related to the permission and M1. We have a cluster which I believe is based on linux and it runs fine.

When I run locally on the M1 and set the permission to `0:0`, no problems.
```
$docker run -it --rm --platform linux/amd64 --entrypoint /bin/sh --user 0:0 nginxinc/nginx-unprivileged:1.23-alpine
/ # mkdir /tmp/temp_proxy
/ #
```

However when I try again with just the unpriviliged `101:101` user, it errors:
```
$docker run -it --rm --platform linux/amd64 --entrypoint /bin/sh nginxinc/nginx-unprivileged:1.23-alpine
/ $ mkdir /tmp/temp_proxy
mkdir: can't create directory '/tmp/temp_proxy': No space left on device
/ $
```

**Comment by alessfg** [comment]
That is quite interesting indeed. Sadly I can't replicate the issue on my end (nor can any of the colleagues I have asked to take this for a spin) so I don't really know that I can even try to start debugging what might be occurring here. 

Are you using Docker desktop or are you using the Docker binary directly? The only thing I can think of is that there might be some default configuration differences between both that are leading to some issues.

**Comment by js-lowes** [comment]
Weird I was running into a similar issue in a `psql` container. I check docker desktop and it said I had plenty of storage space, but I ran `docker system prune` just in case and that seemed to solve the issue. Thanks for looking into it anyways, I appreciate the help!
