### ISSUE TITLE
Typo in the README

### ISSUE THREAD

**Issue by EdwinWalela** [nginxinc/docker-nginx-unprivileged#131]
### Describe the bug

It's actually a minor typo of the word 'override' on `README.md` under `Common Issues`

I believe this statement:

> If you overrive the default nginx.conf file you may receive the message nginx: [emerg] open() "/var/run/nginx.pid" failed (13: Permission denied), in this case you have to add the line pid /tmp/nginx.pid into your config.

Should read:

> If you **override** the default nginx.conf file you may receive the message nginx: [emerg] open() "/var/run/nginx.pid" failed (13: Permission denied), in this case you have to add the line pid /tmp/nginx.pid into your config.

**Comment by alessfg** [comment]
Haha good catch!
