### ISSUE TITLE
Image 1.23-alpine manifest not found

### ISSUE THREAD

**Issue by HontoNoRoger** [nginxinc/docker-nginx-unprivileged#134]
Pulling the image with an old Docker version 1.13.1 on CentOS7 (used by an old Openshift 3.11 version), I get:

```
manifest for docker.io/nginxinc/nginx-unprivileged:1.23-alpine not found
```
The same happens for 1.22, but 1.21 still works.

I then tried to check this via curl:

```bash
[root@machine]# curl -sSLkH "Authorization: Bearer ${TOKEN}" https://registry-1.docker.io/v2/nginxinc/nginx-unprivileged/manifests/1.23-alpine
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"OCI index found, but accept header does not support OCI indexes"}]}
[root@machine]# 
[root@machine]# curl -sSLkH "Authorization: Bearer ${TOKEN}" https://registry-1.docker.io/v2/nginxinc/nginx-unprivileged/manifests/1.21-alpine
{
   "schemaVersion": 1,
   "name": "nginxinc/nginx-unprivileged",
   "tag": "1.21-alpine",
   "architecture": "amd64",
   "fsLayers": [
      {
         "blobSum": "sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4"
...
```

I do see the image just fine on the site https://hub.docker.com/layers/nginxinc/nginx-unprivileged/1.23-alpine/images/sha256-9f8aeef55205665bd310de24bde1187ada6c30096ae8fb2b8f4ce183a75dfb41?context=explore as well as being able to properly retrieve it with Docker version 23.0.1.

Was there any change in the build system between 1.21 and 1.23 which could explain incompatibilities for manifests for older Docker versions? Or any other issue which would explain this behavior?
Thank you!

**Comment by alessfg** [comment]
I just checked the latest commit featuring `1.21.x` (https://github.com/nginxinc/docker-nginx-unprivileged/tree/c2e8e989ac24ce9e1cbb31f5536c8f9a3bebdbc0) and nothing has changed for the most part with one exception, manifests are now signed (https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/.github/workflows/alpine-mainline.yml#L98-L119). I wonder if that might be related to your issue?

**Comment by alessfg** [comment]
Closing this for the time being since there's not much I can do on my end. Hopefully my pointer helped you figure out what the issue might have been :)
