### ISSUE TITLE
Latest alpine image does not start on OpenShift

### ISSUE THREAD

**Issue by imunic** [nginxinc/docker-nginx-unprivileged#14]
The alpine based image fails to start with:

`mkdir() "/var/cache/nginx/proxy_temp" failed (13: Permission denied)`

Looking at the Dockerfile of both, the stretch based image contains the following:

https://github.com/nginxinc/docker-nginx-unprivileged/blob/c54d8ac20367dde8de8573179c63e39709aadd8d/stable/stretch/Dockerfile#L95

While the equivalent chmod line is missing from the alpine image.

**Comment by alessfg** [comment]
Thanks for reporting this issue @imunic! I created a PR and pushed the modified Docker images to Docker Hub. Can you try pulling the newest Alpine images and let me know if it works?

**Comment by pferreir** [comment]
Still failing for me.
