### ISSUE TITLE
UID and GID are not respected in user creation in alpine slim image

### ISSUE THREAD

**Issue by masonen** [nginxinc/docker-nginx-unprivileged#144]
### Describe the bug

When passing systems UID and GID as build ARG to one the images based on the alpine-slim image the UID and GID of the nginx user defaults still to the hardcoded 101.

### To reproduce

1. build any of the provided images and pass UID and GID as custom arguments (e.g. 1000:1000)
2. run container with sh command to skip entrypoint
3. check id -u and id -g, they will still be the default values instead of the passed in values

### Expected behavior

I would expect the user to be created with the 

### Your environment

- Version of Docker 23.05
- 3.17-any
- x86

### Additional context

There seems to be a pretty ovious fix. The command creating the user is using UID and GID as env var not as build arg
https://github.com/nginxinc/docker-nginx-unprivileged/blob/9a8b6d67c174e9fde27b44bdd61bc3e372126e3a/mainline/alpine-slim/Dockerfile#L19
https://github.com/nginxinc/docker-nginx-unprivileged/blob/9a8b6d67c174e9fde27b44bdd61bc3e372126e3a/mainline/alpine-slim/Dockerfile#L20

In my own dockerfile i fixed it like so
 ```Dockerfile
 FROM nginxinc/nginx-unprivileged:alpine3.17

ENV UID=${UID}
ENV GID=${GID}
 ```

This created the user as expected. I think this fix could be added in the slim base image.
WDYT?

**Comment by alessfg** [comment]
I can't seem to reproduce this error on my side?

If I build the Alpine mainline slim image using:
```bash 
/ $docker build -t nginx --build-arg UID=1000 --build-arg GID=1000 .
```
run the image using:
```bash
/$ docker run --rm -it nginx sh
```

and then check both the UID and GID I get the correct values:
```bash
/ $ id -g
1000
/ $ id -u
1000
```

Do you have any more info that might help me reproduce the error?
