### ISSUE TITLE
Support images based on ubuntu instead of debian

### ISSUE THREAD

**Issue by raoganeshr** [nginxinc/docker-nginx-unprivileged#145]
### Is your feature request related to a problem? Please describe
ngnix images based on debian tend to have a lot of vulnerabilities that are due to the base image. It is difficult to understand if those issues actually affect ngnix or no.

A clear and concise description of what the problem is. Ex. I'm always frustrated when ...

### Describe the solution you'd like
Instead of using debian, can we use ubuntu as the base image. Ubuntu images tend to fix most of the issues and also at a faster cadence.

Support ubuntu base image based versions of ngnix images.

### Describe alternatives you've considered
We currently use alpine version.

**Comment by alessfg** [comment]
These images are a port of the upstream docker-nginx repo so I would suggest creating a similar issue in the respective repo https://github.com/nginxinc/docker-nginx?

**Comment by thresheek** [comment]
See https://github.com/docker-library/official-images/pull/1462 for some discussion on the matter.

**Comment by raoganeshr** [comment]
@thresheek so seems it was originally supported but removed to keep the list small. So which of the tags should I use for debian based to have the list number of reported vulnerabilities from base OS? Or do all debian based tags use the same base debian image?

**Comment by thresheek** [comment]
We proposed extending to some other OSes/images, but that never happened, so no, it was not supported/removed.

All debian-based images share the same base debian image, so there wouldnt be any differences.
