### ISSUE TITLE
Update UID and GID to 10001 (>10000)

### ISSUE THREAD

**Issue by yossicohn** [nginxinc/docker-nginx-unprivileged#149]
### Is your feature request related to a problem?
[https://kubesec.io](https://kubesec.io/basics/containers-securitycontext-runasuser/
)
Run as a high-UID user to avoid conflicts with the host’s user table

UIDs below 10,000 are a security risk on several systems, because if someone does manage to escalate privileges outside the Docker container their Docker container UID may overlap with a more privileged system user's UID granting them additional permissions.
For best security, always run your processes as a UID above 10,000. ...

### Describe the solution you'd like
set the Dockerefile UID/GID to 10001 instead of 101

### Describe alternatives you've considered
N/A

### Additional context
We would like to deploy this in k8s, and we need the image to have a UID>10000 for security reasons

I have a PR ready, would be happy to contribute

**Comment by alessfg** [comment]
Hi @yossicohn -- you can already change the UID by rebuilding the images and using the UID and GID build args https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/mainline/alpine-slim/Dockerfile#L14-L15

Changing the default values could become a breaking change for multiple production environments, and, in any case, you shouldn't really have to worry about overlapping UIDs in K8s environments https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/

**Comment by yossicohn** [comment]
@alessfg thanks a lot
