### ISSUE TITLE
15-local-resolvers.envsh is not executable

### ISSUE THREAD

**Issue by kevinbosman** [nginxinc/docker-nginx-unprivileged#150]
### Describe the bug

`15-local-resolvers.envsh` is not executable, so it cannot be sourced during startup, and is then ignored.

### To reproduce

1. Deploy NGINX Unprivileged Docker image: `docker run --rm nginxinc/nginx-unprivileged:latest`
2. See error in the logs:
    ```
    /docker-entrypoint.sh: Ignoring /docker-entrypoint.d/15-local-resolvers.envsh, not executable
    ```

### Expected behavior

`15-local-resolvers.envsh` should be sourced and executed, same as on the upstream nginx image. Logs should read:
```
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
```

### Your environment

- Version of Docker: Docker Desktop v24.0.2 (WSL)
- Version of the NGINX Unprivileged Docker image: latest (bookworm) linux/amd64 (`sha256:e691ae3a76acf217636a687a543416ce3a8086b0adf2a23ab7c24dafadf6659b`)
- Target deployment environment/platform: Any

### Additional context

I believe this affects all the published variants of `nginxinc/nginx-unprivileged`

**Comment by alessfg** [comment]
New images are being built right now! The issue should be fixed, but lets wait until they finish building to be sure.

**Comment by alessfg** [comment]
Fixed!
