### ISSUE TITLE
Branding?

### ISSUE THREAD

**Issue by conradj3** [nginxinc/docker-nginx-unprivileged#151]
Why are the Nginx community images under the docker `nginxinc` but not officially branded by Nginx with company logos? 

Example:
https://hub.docker.com/r/nginxinc/nginx-unprivileged

**Comment by alessfg** [comment]
I really don't have a good answer for you. Yes, they should be branded, but it's always been low enough in the priority list that it's not made it out of the backlog. I'll see if I can get the Docker hub page updated asap.

**Comment by alessfg** [comment]
Done!
