### ISSUE TITLE
Please add bookworm-stable tag with current stable version based on Debian 12

### ISSUE THREAD

**Issue by nudgegoonies** [nginxinc/docker-nginx-unprivileged#152]
### Is your feature request related to a problem? Please describe

We rely on stable. Currently version 1.24.0 is only available in stable and stable-bullseye tags that are based on Debian 11. But there is no stable 1.24.0 image based on Debian 12.

### Describe the solution you'd like

Please add bookworm-stable tag with current stable version based on Debian 12

**Comment by thresheek** [comment]
`1.24` tags will only be moved to Debian 12 when we have a new 1.24 release out.  I'm not sure this will happen any time soon though.

**Comment by alessfg** [comment]
I figured as much, but it's good to get confirmation!

**Comment by alessfg** [comment]
Closing this for the time being. Images here will be updated whenever the Docker NGINX images get updated!
