### ISSUE TITLE
Please verify that this repo and associated Docker image are from the official "Nginx" project

### ISSUE THREAD

**Issue by srkiNZ84** [nginxinc/docker-nginx-unprivileged#16]
Hi,

In light of the recent "runc" vulnerability, we have started the task of ensuring that all of our containers are running unprivileged/non-root processes.

For one of our containers we are using the "official" Nginx image as the base (https://hub.docker.com/_/nginx) but would like to switch to this one as it runs "unprivileged".

However, we note that it's very hard to tell that the Dockerhub image (https://hub.docker.com/r/nginxinc/nginx-unprivileged) comes from this repository and also that the "nginxinc" accounts in Dockerhub and GitHub are the "official" Nginx ones.

Could we please have some kind of verification that:
* The DockerHub repository (https://hub.docker.com/r/nginxinc/nginx-unprivileged) is associated and originates from this GitHub repository (https://github.com/nginxinc/docker-nginx-unprivileged/)
* That the DockerHub and GitHub "nginxinc" accounts are associated/owned by [Nginx](https://nginx.org/) 
* That only Nginx maintainers are able to commit/merge to this repository

I'm not sure what the best way to do this is. Currently it seems that just having the "official" tag in DockerHub is enough. Otherwise some documentation on the Dockerhub image page that points back to this repository perhaps?

Thank you and please let me know if this is a stupid question or if you need any more information or something doesn't make sense.

**Comment by alessfg** [comment]
Hi @srkiNZ84!

There's not much that we can do to add more verification steps. At any rate let me try to address your points one by one.

>* The DockerHub repository (https://hub.docker.com/r/nginxinc/nginx-unprivileged) is associated and originates from this GitHub repository (https://github.com/nginxinc/docker-nginx-unprivileged/)

The GitHub README points to the Docker Hub repository. For better tracing purposes I've also added this GitHub repo to the Docker Hub README.

>* That the DockerHub and GitHub "nginxinc" accounts are associated/owned by [Nginx](https://nginx.org/)

`nginxinc` is the business side of `nginx`. Have a look at the other repositories on GitHub and it should become rather obvious that *we are* nginx.

>* That only Nginx maintainers are able to commit/merge to this repository

It's a public repository so everybody can potentially submit a PR. However rest assured that only NGINX maintainers have full access to the repository.

Does this satisfy your concerns? If not, what would you say is would be a trustful way to verify?

**Comment by srkiNZ84** [comment]
Thank you very much for that response @alessfg! That does satisfy my concerns.

> what would you say is would be a trustful way to verify?

Some more suggestions from our security team (not sure if these are practical or not, please feel free to ignore any that are too much hassle) are:
* Make the image in Docker Hub a "Docker Official Image" like the main "Nginx" one is:

<img width="340" alt="screen shot 2019-02-18 at 4 40 05 pm" src="https://user-images.githubusercontent.com/163910/52926745-f717f280-339b-11e9-949d-f66475deb301.png">

* Instead of having a separate repository for the "unprivileged" Docker image, make it a "tag" on the main image
* Add the Nginx logo to the DockerHub and GitHub accounts (while this doesn't technically make things more secure, it does make the accounts "look" like what you would expect them to look like)
* Instead of having the "unprivileged" Dockerfile in a separate repository, have it in the same main repository as the rest of the Nginx code

I think you are doing an amazing job and again, thank you very much for making this Dockerfile/code public. Please do not interpret the above as criticism or ungratefulness, the whole Nginx team and company is an inspiration and an incredible asset to our industry.

**Comment by stephenmoloney** [comment]
These suggestions would enhance trust. In general, for the security conscious, building and hosting your own image in a private registry is a straight forward approach.

**Comment by srkiNZ84** [comment]
> building and hosting your own image in a private registry is a straight forward approach.

This is true and a good point. I'm trying to avoid this personally, as if I did this for all underlying components that go into our solution it would just add to maintenance/upkeep burden for little benefit realistically in terms of risk reduction (in my opinion and also in the current context/industry/threat model that I am working in). 

I would much rather have a (good enough) trusted/verified "supply chain" from Nginx to us of all new features/bugfixes/patches etc...

**Comment by alessfg** [comment]
Let me have some discussions and see how/if we can implement any of your suggestions @srkiNZ84 😄
