### ISSUE TITLE
Publish image to a registry that is not rate-limited

### ISSUE THREAD

**Issue by BlaineEXE** [nginxinc/docker-nginx-unprivileged#163]
### Is your feature request related to a problem? Please describe

Rook uses this image (specifically, `nginxinc/nginx-unprivileged:stable-alpine`) as part of a tool that validates user networking environments. Many users have reported that pods fail to run due to the image being rate limited via docker hub.

Images are also available via GitHub's registry and AWS's registry, but both of those locations are also rate limited.

Rook bug report: https://github.com/rook/rook/issues/13052

### Describe the solution you'd like

The image should be hosted in a location that is not rate limited. I can suggest 2 options:
- Use Docker Hub's open source program to allow unrestricted pulling of the existing `nginxinc/nginx-unprivileged` images, which are upstream images to the best of my knowledge. Ref: https://www.docker.com/blog/expanded-support-for-open-source-software-projects/
- Release the image to quay.io, which does not rate limit images

### Describe alternatives you've considered

Unfortunately, I cannot contribute a PR to this repo to fix the issue because it requires administrators to create/modify account privileges for Docker (or Quay). 

Rook can self-host a version of the nginx-unprivileged image in its repository using skopeo or some other mirroring tool. However, it seems in the best spirit of open source software to alert nginx of the issue and allow them time to resolve it for everyone, rather than have our own fork. If maintainers of this repo are not willing or are too slow to respond to this request, Rook can fall back to this plan.

### Additional context

N/A

**Comment by alessfg** [comment]
I think it should be feasible to add these images to Quay!

**Comment by BlaineEXE** [comment]
Glad to hear it. Please let me know if I can be helpful to speed up the process. I can't create the repo or tokens, but I can create a PR to add it to the CI pipelines as long as I know what the github secrets are named for auth-ing with quay.

**Comment by alessfg** [comment]
That'll be helpful! I'll keep you posted -- looks like we don't have an active Quay org so it might take a few weeks.

**Comment by alessfg** [comment]
Good news! Images are now available on Quay 😄
