### ISSUE TITLE
Alpine 3.19 Upgrade

### ISSUE THREAD

**Issue by eromano** [nginxinc/docker-nginx-unprivileged#180]
### Describe the bug

A clear and concise description of what the security vulnerability is.

### To reproduce
Alpine 3.18 is affected by some medium vulenrarbility can you guys pleas bump it? 
### Additional context

Does this security vulnerability relate to one of the NGINX libraries specified in the [`SECURITY`](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/SECURITY.md) doc?

**Comment by alessfg** [comment]
https://github.com/nginxinc/docker-nginx does not yet support Alpine 3.19. Usually the distribution version is updated at the same time as NGINX, so I don't think the images will be updated to Alpine 3.19 until then.

For future reference, unless you find some specific security vulnerabilities that correspond to the list in the SECURITY doc, I would advise against using the security issue form.
