### ISSUE TITLE
mainline-alpine image uses an old version of Alpine and OpenSSL

### ISSUE THREAD

**Issue by jumal** [nginxinc/docker-nginx-unprivileged#20]
The mainline-alpine image is using an old version of Alpine and OpenSSL.

```
docker run -it nginxinc/nginx-unprivileged:mainline-alpine /bin/s

/ $ more /etc/alpine-release
3.8.2

/ $ nginx -V
nginx version: nginx/1.15.8
built by gcc 6.4.0 (Alpine 6.4.0)
built with OpenSSL 1.0.2q  20 Nov 2018
```

Comparing this image's Dockerfile with the non unprivileged image's Dockerfile shows that this image takes the base image is an argument, which is probably incorrectly set by the build system:

```
diff docker-nginx/mainline/alpine/Dockerfile docker-nginx-unprivileged/mainline/alpine/Dockerfile
1c1,2
< FROM alpine:3.9
---
> ARG IMAGE=alpine:3.9
> FROM $IMAGE
```

**Comment by alessfg** [comment]
Hi @jumal!

I think I've been able to trace why the `mainline-alpine` image was still set to Alpine 3.8.2 - the Docker manifests in Docker Hub were being cached and not updating correctly. I pushed new manifests and tweaked the build script, can you try pulling again the image and see if it's been properly updated to use Alpine 3.9? It seems to be working correctly on my end ;)

Cheers,
Alessandro.

**Comment by jumal** [comment]
Hi @alessfg.

The problem is now solved.

Thank you very much
