### ISSUE TITLE
nginxplus version

### ISSUE THREAD

**Issue by ITG-jnadlaon** [nginxinc/docker-nginx-unprivileged#209]

**Comment by alessfg** [comment]
Hey @ITG-jnadlaon! You should be able to combine the Dockerfiles here with the Dockerfiles here https://docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-docker/#creating-custom-nginx-plus-docker-image 😄

**Comment by ITG-jnadlaon** [comment]
thank you on your advise will try that.
