### ISSUE TITLE
nginxinc/nginx-unpriviledged:1.14-alpine is not version 1.14

### ISSUE THREAD

**Issue by kalioz** [nginxinc/docker-nginx-unprivileged#21]
I don't know where to signal this, but as of 26/04/2019 the nginxinc/nginx-unprivileged:1.14-alpine has a nginx version of 1.16.0 (yesterday it was 1.14.2)
version 1.14.2 before 26/04 (stored locally)
![image](https://user-images.githubusercontent.com/24780504/56794435-6b449b80-680e-11e9-82c5-bb550f4cfe08.png)

version 1.16.0 today
![image](https://user-images.githubusercontent.com/24780504/56794412-61bb3380-680e-11e9-9e84-d1b1290c183f.png)

**Comment by alessfg** [comment]
Hi @kalioz!

I'll update and fix the images and tags asap. Do you specifically need `nginx` 1.14 or would 1.16 work for you? In either case I would recommend using a different tag for now. `1.16.0-alpine` should work for `nginx` 1.16 images and `1.14.2-alpine` should work for `nginx` 1.14 images. Let me know if that helps!

Kind Regards,
Alessandro.

**Comment by alessfg** [comment]
I've made some fixes to the build process and tags should be correctly applied from now on. However, as part of the fixes, only tags from the last release onwards will be available (1.15.12 for NGINX mainline and 1.16.0 for NGINX stable).

**Comment by kalioz** [comment]
thanks !
