### ISSUE TITLE
Images with tags fixing alpine versions are missing

### ISSUE THREAD

**Issue by tete17** [nginxinc/docker-nginx-unprivileged#211]
### Is your feature request related to a problem? Please describe

We used to be able to rely on `nginxinc/nginx-unprivileged:1.24.0-alpine3.17-slim` to be available just like the upstream releases.

It seems now only the unversioned `nginxinc/nginx-unprivileged:1.26.0-alpine-slim` is available.

### Describe the solution you'd like

Either recreate these images with tags that also fix the alpine version or specify which of the upstream tags this project supports.

### Additional context

We rely on renovatebot update to keep our system updated and it is only prompting us to update to `1.25.1-alpine3.17-slim`

**Comment by alessfg** [comment]
Aiming to have this fixed by EoD Monday! 🙂

**Comment by alessfg** [comment]
New images should be live in a few hours!
