### ISSUE TITLE
/var/cache/nginx folder owned by root:root

### ISSUE THREAD

**Issue by pepijnblom** [nginxinc/docker-nginx-unprivileged#23]
After this commit was applied permissions aren't what they used to be: 
https://github.com/nginxinc/docker-nginx-unprivileged/commit/090a5452a97ec4365ab27fbbdddec2c1bfe3f74f

The `/var/cache/nginx` directory is now owned by `root:root` causing our containers to fail.
I see the chown & chmod lines were deleted at the bottom of the Dockerfile.

```
2019/07/04 12:44:31 [emerg] 6#6: mkdir() "/var/cache/nginx/proxy_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/proxy_temp" failed (13: Permission denied)
```

**Comment by csullivannet** [comment]
I was able to resolve this issue by making sure that `/var/cache/nginx` is created along with the user and that permissions are assigned after the user is created:
https://github.com/nginxinc/docker-nginx-unprivileged/pull/24

I was also able to work around this issue by assigning the correct permissions to a host level volume and bind mounting it, e.g. in my compose file:
```
    volumes:
      - /opt/nginx/cache:/var/cache/nginx
```

and permissions on my host via [userns remapping](https://docs.docker.com/engine/security/userns-remap/):
```
[root@web nginx]# ll /opt/nginx/
drwxr-xr-x. 7 100101 100101  115 Jul  5 14:48 cache
```

**Comment by pepijnblom** [comment]
Yeah I just did a 
```
mkdir -p /var/cache/nginx
chown nginx:nginx /var/cache/nginx
```

**Comment by Yatekii** [comment]
All this does not work at all ... The same error persists.

**Comment by alessfg** [comment]
Hm interesting -- there haven't been any new issues re permissions since this issue was resolved, and there's been no changes to the way permissions are handled either. Where are you running your containers and what error are you getting? And what NGINX config are you sharing with the running container?

**Comment by Yatekii** [comment]
I have fixed this meanwhile. The problem was that I passed a `--user` to `docker run` which made the permission error appear. I am am not exactly sure what I am supposed to do to properly set this up, but it works without passing a user :)

Sorry for the rude false alarm.
