### ISSUE TITLE
Latest 1.27.2 Docker Image is not available

### ISSUE THREAD

**Issue by jacquesg** [nginxinc/docker-nginx-unprivileged#249]
### Describe the bug

The latest tags are not available.

### To reproduce

N/A

### Expected behavior

Docker tag `nginxinc/nginx-unprivileged:1.27.2*` tags are available

### Your environment

N/A

### Additional context

N/A

**Comment by alessfg** [comment]
Hey @jacquesg! There tends to be a lag between new releases/the Docker image being updated and the unprivileged image being updated. That being said, keep an eye out for #250. If the pipeline succeeds the 1.27.2 images should be available later today.

**Comment by jacquesg** [comment]
Awesome, thank you :)
