### ISSUE TITLE
Shouldn't these two lines be flipped?

### ISSUE THREAD

**Issue by aqeelat** [nginxinc/docker-nginx-unprivileged#254]
Wouldn't flipping these lines make more sense?
If ipv6 is enabled then we wouldn't need to check if the file is writable. The exit message will be more informative, instead of sending the user in a wild hunt.

https://github.com/nginxinc/docker-nginx-unprivileged/blob/338d5c7e6a0f1c1294c3127e1481ea0739a23d87/entrypoint/10-listen-on-ipv6-by-default.sh#L26-L30

**Comment by alessfg** [comment]
I would suggest opening this issue in the upstream [Docker NGINX](https://github.com/nginxinc/docker-nginx) repo. All changes to core functionality have to be done on that repo and they then get merged to this repo.

**Comment by aqeelat** [comment]
Can you please move it to that repo?
https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/transferring-an-issue-to-another-repository
