### ISSUE TITLE
1.17.3/1.16.1 release not complete?

### ISSUE THREAD

**Issue by davesteinberg** [nginxinc/docker-nginx-unprivileged#26]
It looks to me like 1.17.3 and 1.16.1 images have been partially, but not completely, released? For instance, I see that the `mainline` tag has been updated to point at a new 1.17.3 image, but there's no `1.17.3` tag, and the `1.17` tag is still pointing at the same image as `1.17.2`. Looks like the same situation for the `-alpine` variants, and probably others?

I'm just looking at these images for the first time today, so apologies if I'm missing something about how they're usually organized or rolled out.

**Comment by alessfg** [comment]
You are not wrong. There's an issue with some of the images at the moment which I didn't find out until some images for `1.17.3` had been released. I've reverted all `mainline` images to `1.17.2` for the time being (to the best of my knowledge). I will keep this issue open till `1.17.3` has been fully released.

**Comment by davesteinberg** [comment]
@alessfg Apologies if this comes off as a nag, but it's now been a few months, 1.17.3 still isn't released, and the official (runs-as-root) nginx image is now at 1.17.5. So, I'm wondering if there's still an issue you're working through (and if so, could you use some help?), or if we should just consider this projected ended and switch to the official image, instead.

**Comment by alessfg** [comment]
Long story short, there seems to be some issues when building `ppc64le` Alpine images on my end. I was waiting to see if an upstream fix would address those issues but alas it's not happened. And, I've also been busy with other work. I'll try to publish updated images over the next week (with the exception of `ppc64le/alpine` that is).

**Comment by davesteinberg** [comment]
@alessfg Thanks so much for the update. That's too bad about ppc64le/alpine, but I really appreciate that you'll publish the other images.

**Comment by alessfg** [comment]
Good news! Managed to figure out what the issue was in the end. Images for `1.17.3` and `1.16.1` should be available on Docker Hub. `1.17.4` and `1.17.5` should be coming in the next few days.

**Comment by davesteinberg** [comment]
Amazing! Thanks so much!

**Comment by alessfg** [comment]
All images on Docker Hub should now be up to date 😄

**Comment by alessfg** [comment]
As of today there's no plans. It's not a common practice to host unprivileged images on the official library. You can also check https://github.com/nginxinc/docker-nginx-unprivileged/issues/19#issuecomment-479536708 for more context.

**Comment by chadlwilson** [comment]
From my perspective it's reasonably common as a number of images we use from official run as non-root by default (e.g `gradle`, `mysql`, `redis` etc), and `library` does have the benefit of having all images be signed/notarized and an additional layer of trust, and generally `official` images are more regularly/reliably rebuilt to pick up upstream security patches (in say `alpine` or other dependencies) - but understand that it comes with some other overheads. 

Thanks for the reply and your work here to get these images up-to-date!

**Comment by alessfg** [comment]
Right, to elaborate on my answer a little bit more, it's not only that it's an unprivileged image, it's also that it runs as a specific user. We are always exploring potential new ways to build these images so that they can be run by any UID and still run NGINX as an unprivileged user. If we achieve that, we'll revisit making these images available on the official Docker library.

**Comment by tandrup** [comment]
When I pull nginxinc/nginx-unprivileged:stable-alpine sh from docker hub I get nginx version 1.16.0
