### ISSUE TITLE
404 for nginxinc/nginx-unprivileged/manifests/1.15.9-alpine

### ISSUE THREAD

**Issue by git001** [nginxinc/docker-nginx-unprivileged#27]
Looks like the image is not available on docker hub as mentioned in #18 is the normal image fixed but not the alpine one.

```
Nov 25 17:13:22 satellite pulp[17431]: nectar.downloaders.threaded:INFO: [0dcfccce] Download failed: Download of https://registry-1.docker.io/v2/nginxinc/nginx-unprivileged/manifests/1.15.9-alpine failed with code 404: Not Found
```

**Comment by alessfg** [comment]
Can you try pulling the latest version? IIRC there was an issue at some stage with previous builds and I had to get rid of them. The oldest version available right now seems to be 1.15.12.

**Comment by git001** [comment]
The problem is that the RH Satellite 6.3 does not offer to limit the pull. As long as the TAG is announced will the Satellite pull it. Please can you remove this TAG from the Docker hub.

**Comment by alessfg** [comment]
It's already not there https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags?page=1&ordering=-last_updated

**Comment by git001** [comment]
@alessfg Okay I see it's not in the GUI but the api still returns that tag.  
you will need `jq` to run the commands below

```
export TOKEN=$(curl -sSLk 'https://auth.docker.io/token?scope=repository%3Anginxinc%2Fnginx-unprivileged%3Apull&service=registry.docker.io'|jq -r '.token')  
curl -sSLkH "Authorization: Bearer ${TOKEN}" https://registry-1.docker.io/v2/nginxinc/nginx-unprivileged/tags/list|jq '.tags[]|select(. == "1.15.9-alpine")'
"1.15.9-alpine"
```

**Comment by alessfg** [comment]
Right, I see that. I can't find a different way to delete those tags. Can you not update the image version on your end?

**Comment by git001** [comment]
Well RH Satellite can't limit pulling specific tags before 6.5, we are on the way to update to RH 6.5.  
Never the less docker hub should not list tags which are no more visible or usable, but I think that's a docker hub issue.

**Comment by alessfg** [comment]
Oh yeah. Sorry about that. I'll keep an eye open to see if there's any updates on Docker's side of things.

**Comment by git001** [comment]
Thanks. let's close this issue as you can't fix IMHO
