### ISSUE TITLE
Dockerhub stable-alpine version latest does not contain 1.16.1, but 1.16.0

### ISSUE THREAD

**Issue by JonasBovin** [nginxinc/docker-nginx-unprivileged#28]
According to stable/alpine/Dockerfile it will build using nginx 1.16.1, but the stable-alpine image in dockerhub, is built using the 1.16.0 which is vulnerable. We can pick the stable-alpine-perl version to avoid running on a vulnerable version (1.16.0), but we would prefer the stable-alpine built in a version that matches the Dockerfile. Tnx.

/Jonas

**Comment by alessfg** [comment]
Should be fixed now 😄
