### ISSUE TITLE
Docker hub tag?

### ISSUE THREAD

**Issue by slaterx** [nginxinc/docker-nginx-unprivileged#3]
Hi,

Is this project published anywhere in Docker Hub? 

If yes, in which tag?

Thanks,
Gleidson

**Comment by alessfg** [comment]
Hi @slaterx!

You can find all these images in Docker Hub here https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags/. I'll add a comment to the README to make it clearer 😄 

Cheers,
Alessandro.
