### ISSUE TITLE
Multpile rewrite Issue

### ISSUE THREAD

**Issue by yograjpatty21** [nginxinc/docker-nginx-unprivileged#32]
I'm trying to run nginx as unprivilaged user and adding multiple rewrite rule inthe nginx.conf.

post building the  image I see just one rewrite rule deleting the remaining.

In local nginx.conf

 rewrite ^/myaccount-messenger/services/rest/1.0/account/accountnumber/(.*) https://messenger.nginx.coxbusiness.com/cbma/account/services/account/messenger/accountnumber/$1 last;
            rewrite ^/myaccount-messenger/services/rest/1.0/user/email/(.*) https://messenger.nginx.coxbusiness.com/cbma/user/services/user/messenger/email/$1 last;
            rewrite ^/myaccount-messenger/services/rest/1.0/user/authenticate/(.*)  https://messenger.nginx.coxbusiness.com/cbma/user/services/user/messenger/authenticate/$1 last;

In the Image:
rewrite ^/myaccount-messenger/services/rest/1.0/account/accountnumber/(.*) https://messenger.nginx.coxbusiness.com/cbma/account/services/account/messenger/accountnumber/$1 last;

**Comment by alessfg** [comment]
How are you copying your nginx.conf to the Docker image? Which Docker image are you using?

**Comment by yograjpatty21** [comment]
Added these steps to Dockerfile

WORKDIR /opt/www

COPY nginx.conf /etc/nginx
COPY proxy.conf /etc/nginx
ADD index.html /opt/www/messenger

**Comment by alessfg** [comment]
Hm if you are copying the conf file as is there's no reason why some rules would be deleted. Can you include your nginx.conf file (edit out any sensitive information) and let me know which Docker image you are using? I'll try to deploy your image on my end and see what I find.

**Comment by yograjpatty21** [comment]
Tried to copy the custom nginx.conf to conf.d and I see the rewrite rules. Will test and update.

I'm using the Alpine Image.

**Comment by yograjpatty21** [comment]
It worked after updating the nginx.conf inside conf.d instead of adding the same in /etc/nginx/nginx.conf

**Comment by alessfg** [comment]
I'm still not entirely sure what was the root cause of your issue but I'm glad to hear you found a solution!
