### ISSUE TITLE
Angular App Image with non root user

### ISSUE THREAD

**Issue by tushi0407** [nginxinc/docker-nginx-unprivileged#33]
I am creating docker image of my angular app using root user.But i want to change it to use non root user.Please help me doing this. Here is my docker file.
`FROM  docker.com/node:latest as node

WORKDIR /app

COPY . .

RUN npm install

RUN npm run ng build -- --prod

#stage 2 : to run application

FROM docker.com/nginx:alpine

COPY --from=node /app/dist/MyApp /usr/share/nginx/htm`

**Comment by alessfg** [comment]
Hey @tushi0407 I'm sorry but I don't think this is the best place to ask that question. If you want to run NGINX as a non root user you can do that by running this image (`nginxinc/nginx-unprivileged:alpine`). If your issue is related to the Node Docker image try asking in that repository directly.
