### ISSUE TITLE
v1.18 fails on systems with IPv6 disabled

### ISSUE THREAD

**Issue by CCoffie** [nginxinc/docker-nginx-unprivileged#35]
With the addition of `listen  [::]:8080;` to the default nginx config the container will boot loop on systems that have IPv6 disabled.

**Comment by thresheek** [comment]
That doesnt happen here on the machines with net.ipv6.conf.all.disable_ipv6=1.  How do you test?

**Comment by Popsiclestick** [comment]
Here is some additional information from my own tests

Docker: `18.06.3.ce`
Kubernetes: `1.17`
OS: `Centos7`

IPv6 disabled -- `GRUB_CMDLINE_LINUX="ipv6.disable=1"`

Running default `nginxinc/nginx-unprivileged` on kube yields
```
:;  kubectl logs nginx-deployment-6785748788-n9fcr
2020/04/29 19:57:26 [emerg] 1#1: socket() [::]:8080 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:8080 failed (97: Address family not supported by protocol)
```

**Comment by thresheek** [comment]
Thanks @Popsiclestick - indeed that happens with ipv6.disable=1 on my systems as well.
I think we'll need to revert the change for now.

Thank you again!

**Comment by Popsiclestick** [comment]
No problem, thanks for the quick responses. Let me know if you need anything else.

**Comment by alessfg** [comment]
I've reverted the IPv6 change for the time being 😄

**Comment by alessfg** [comment]
I pushed a new update on Monday that should dynamically set IPv6 on supported systems. Closing this issue 😄
