### ISSUE TITLE
unpriviledged version still looks for nginx.pid under /var/run/nginx.pid

### ISSUE THREAD

**Issue by robertofabrizi** [nginxinc/docker-nginx-unprivileged#36]
As the title says, I'm using the unprivileged image but it still fails to start due to checking for nginx.pid in the wrong path:

```
[devops@postetet ~]$ docker ps -a | grep nginx
bdbf5c66375c        b05a847a4c43                                                                                                                                "nginx -g 'daemon ..."   About a minute ago   Exited (1) About a minute ago                       k8s_nginx-service_nginx-e-69f9cbbfc9-8gxn9_mlp-sda-svil_7d818854-9b7b-11ea-8e4f-

[devops@postetet ~]$ docker logs bdbf5c66375c
2020/05/21 16:16:45 [emerg] 1#1: open() "/var/run/nginx.pid" failed (13: Permission denied)
nginx: [emerg] open() "/var/run/nginx.pid" failed (13: Permission denied)

[devops@postetet ~]$ docker images | grep b05a847a4c43
docker.io/nginxinc/nginx-unprivileged                                     latest              b05a847a4c43        2 weeks ago         132 MB

```

**Comment by alessfg** [comment]
Hm I can't seem to reproduce your error, and seeing how there's not been any changes as far as PID configuration goes in quite some time and there's been no issues opened with this error, I think that the issue might be on your end. 

The NGINX PID is created in `/tmp/nginx.pid` by default (https://github.com/nginxinc/docker-nginx-unprivileged/blob/master/mainline/buster/Dockerfile#L104). Are you perhaps sharing an `nginx.conf` volume/file when running the image? If so, check what you have set as your PID there (by default, if empty, the PID will be at `/var/run/nginx.pid`). Otherwise, I can't think of many other reasons for your issue :/

**Comment by robertofabrizi** [comment]
Ahhh my bad then, I thought that it was defaulting to /tmp regardless of providing a custom nginx.conf or not.

**Comment by alessfg** [comment]
Glad you figured it out!

**Comment by robertofabrizi** [comment]
Still isn't fully clear to me tho, I've started the container and checked what is present in the official nginx.conf, and merged the official one with mine to not miss overriding defaults like the pid one. 

In the official there is this line:

>     include       /etc/nginx/mime.types;

which I added to mine, yet it failed to start saying that that file wasn't found. If I comment that line it works.

**Comment by alessfg** [comment]
That should work just fine (and is working on my end too). I would recommend running an image as is (don't share your NGINX configuration file) and peeking into the NGINX directory in `/etc/nginx`. 

My current best guess is that when you share the volume you're overwriting the `/etc/nginx` directory and thus accidentally deleting the `mime.type` file.

**Comment by robertofabrizi** [comment]
Makes sense, thanks a lot @alessfg

**Comment by namedgraph** [comment]
@alessfg doesn't fixing this require having `pid /tmp/nginx.pid` in the `nginx.conf` file? This post seems to suggest so:
https://aandhsolutions.com//run-nginx-as-unprivileged-user-in-docker-container-on-kubernetes/

**Comment by alessfg** [comment]
Yes, and it is there https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/mainline/debian/Dockerfile#L113 😄

**Comment by mirekphd** [comment]
An approach of making container rootless should not assume that the customized config file is left unchanged at run time. In fact a server config file is very likely to be overwritten by a custom one, undoing all your changes to run nginx rootless. What are the benefits from building a separate container whose main is removed by most who use it? And there are disadvantages of such a fork, like lagging behind the latest secure base image (as is currently the case).

**Comment by alessfg** [comment]
> An approach of making container rootless should not assume that a customized config file used for this purpose is left unchanged at run time. In fact a server config file is very likely to be overwritten by a custom one, undoing all your changes required to run nginx rootless that are passed via a sed-edited nginx.conf [here](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/mainline/alpine/Dockerfile?rgh-link-date=2022-06-16T09%3A55%3A47Z#L127). 

On a fundamental level, I agree. That being said, NGINX does require those changes to be made to run as non root, no matter what you do, and as of today, the default NGINX config that ships with NGINX is not going to change to cater to non root scenarios. If you change the default NGINX config that ships within this image, I would also hope you understand what changes you need to do to ensure NGINX runs correctly in an unprivileged image. Furthermore, we recommend people do not tweak the default `nginx.conf` unless they absolutely need to. That is why the default installation pattern has the web server config in the `/etc/nginx/conf.d/` directory.

> There are also disadvantages of maintaining a fork, like lagging behind the latest secure base image, e.g.:
[https://github.com/nginxinc/docker-nginx-unprivileged/issues?q=cve+is%3Aissue+is%3Aclosed+](https://github.com/nginxinc/docker-nginx-unprivileged/issues?q=cve+is%3Aissue+is%3Aclosed+sort%3Aupdated-desc)

If you do a similar search in the main Docker NGINX repo you will find CVEs are also routinely reported (in fact, most of them are the same as the ones reported here) https://github.com/nginxinc/docker-nginx/issues?q=cve+is%3Aissue+is%3Aopen+sort%3Aupdated-desc+ -- I will also add that about 99% of these CVEs have nothing to do with any library used by NGINX so if you are using the image as you should (e.g. only using it to run NGINX and nothing more) you should not be at risk. 

Docker has a policy of not allowing images to fit specific use cases (e.g. run in unprivileged environments) inside their official library, so unless that changes, a fork like this is the best we can do 😄
