### ISSUE TITLE
Latest nginx 1.18-alpine docker image has port 80 instead of 8080

### ISSUE THREAD

**Issue by vasicvuk** [nginxinc/docker-nginx-unprivileged#39]
Latest nginx 1.18-alpine docker image has port 80 instead of 8080

Also stable-alpine tag has port 80 in default.conf

**Comment by btsuhako** [comment]
we experienced the same thing in one of our built images recently. we're rolling back to `nginxinc/nginx-unprivileged:1.17` until there's a fix

**Comment by alessfg** [comment]
Follow #37 for updates on a couple issues present on the last release. That being said, you should not be seeing port 80 instead of 8080 (and I can't seem to reproduce that error). Could you please share the logs of the containers that have the wrong port? And could you also share how you are launching the containers (command/environment)?

**Comment by vasicvuk** [comment]
Also we get: 
nginx: [emerg] open() "/var/run/nginx.pid" failed (13: Permission denied)

We are running with Docker normal run command without any additional argument

**Comment by alessfg** [comment]
Yeah, it seems as if for some reason the entrypoint scripts are not being properly run. Could you share your container logs?

**Comment by vasicvuk** [comment]
Oh now I see I have used sh to cat the default.conf that is why the port 80 was in the file. Docker-entrypoint.sh was not executed.
We are using this image as base one and we have custom init.sh script that is running nginx at the end and also doing some modifications
This call of init.sh file is part of CMD command of our image. This worked fine until now

**Comment by vasicvuk** [comment]
Just to confirm 1.17 version works fine but it worked on 1.18 also before.

**Comment by alessfg** [comment]
Yup that would make sense. 1.18 images were also updated.

**Comment by alessfg** [comment]
I'm partially reverting some of the changes while I do some further testing -- aka moving back the unprivileged config changes to the main Dockerfile. The entrypoint scripts will always graciously exit right now (cue no dynamic IPv6 configs), but at least the images should work in the meantime.
