### ISSUE TITLE
Still giving me errors on openshift 

### ISSUE THREAD

**Issue by ZackAfro** [nginxinc/docker-nginx-unprivileged#4]
Hi, 

I just pulled this image and deployed it to openshift,

But its still giving me this error: 

[emerg] 1#1: mkdir() "/var/cache/nginx/proxy_temp" failed (13: permission denied)

Thats all info I have, any way i can find more to trouble shoot this with ? 

Regards,
Neil Beukes

**Comment by ZackAfro** [comment]
Hi All, So this Image didn't work for me on openshift, I switched to the bitnami/nginx image and that works great.

**Comment by mfrancis95** [comment]
I'm having this issue too. Would like to see it fixed.

**Comment by stephenmoloney** [comment]
is this fixed now ?
