### ISSUE TITLE
Current 1.18 failed with 10-listen-on-ipv6-by-default.sh: 2: not found

### ISSUE THREAD

**Issue by AllexVeldman** [nginxinc/docker-nginx-unprivileged#44]
With the current 1.18 (`@sha256:73948ceb33ff13d977099d5c2a65faa62f9f04b8b5deea9be8df811a6a81659d`) I get:
```
│ /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration                                                                                                         │
│ /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/                                                                                                                                │
│ /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh                                                                                                                    │
│ /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh: 21: /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh: 2: not found                                                                             │
│ stream closed
```

Reverting back to `@sha256:e1b0dc152caec58a182c130532140da5f39a780db554bd6d045830655f99069c` resolved it for me.

Can this be related to #37 ?

_Originally posted by @AllexVeldman in https://github.com/nginxinc/docker-nginx-unprivileged/issues/37#issuecomment-645845425_

**Comment by thresheek** [comment]
That's due to a typo I introduced in https://github.com/nginxinc/docker-nginx/commit/172571e53c1c6dacc86bcef2b09abf91c451bd69.

@alessfg please sync the changes once again, sorry about that.

**Comment by ujoergen** [comment]
Also seeing this issue.

**Comment by alessfg** [comment]
Pushed new images with the fix included!
