### ISSUE TITLE
Can we merge effort with distroless images ?

### ISSUE THREAD

**Issue by abdennour** [nginxinc/docker-nginx-unprivileged#49]
You did great job by complying with container runtiime security:
- container port must be over 1024 
- Default user is a random user (1001)
- Files used by the main process are owned by group root but not user root.
- and others that you documented

## However, ..
I want also to use a distroless image ( without specific linux distribution ) 

> "Distroless" images contain only your application and its runtime dependencies. They do not contain package managers, shells or any other programs you would expect to find in a standard Linux distribution. [Reference](https://github.com/GoogleContainerTools/distroless)

This type of images is not only reduce the surface of attack but it also comply with defense in depth principal. 

This is currently what i am using 

```sh
FROM kyos0109/nginx-distroless:1.16.1-1 as release
WORKDIR /opt/app
COPY --from=build /code/build/. .
```

Reference: https://github.com/kyos0109/nginx-distroless

**Comment by alessfg** [comment]
These images are meant to stay as similar as possible to the upstream official NGINX docker images. As such, sadly, I don't think this is going to happen anytime soon.

**Comment by user451421541757324** [comment]
@alessfg It’s been six years since this issue was opened: has anything changed? Is it possible now?
