### ISSUE TITLE
Parameterize uid/gid of nginx user

### ISSUE THREAD

**Issue by darioseidl** [nginxinc/docker-nginx-unprivileged#55]
We have a custom image based (with some config templates and our build in /var/www) based on the nginx-unprivileged image. The nginx-unprivileged creates a nginx user with gid and uid 101.

In a new project we would like to run the image on a Debian buster host, where the uid 101 is already taken by the host user systemd-timesync. It's not creating any problem at the moment, but just as a best practice, I would like to create matching users between our host and Docker containers to restrict the users in the containers to their files.

Now, I'm not sure what would be the best way to go about this. I don't want to mess with the systemd user. I could, of course, create my own version of the nginx-unprivileged, but I'd rather stay with upstream as much as possible. There is also the option to [remap the uids](https://docs.docker.com/engine/security/userns-remap/), but I haven't looked into that yet.

It would be easiest if we could just have a different uid/gid for the nginx user. Would you be willing to parameterize the uid/gid in the nginx-unprivileged Dockerfile? For example, like this: 

```
...
ARG UID=101
ARG GID=101

RUN set -x \
# create nginx user/group first, to be consistent throughout docker variants
    && addgroup --system --gid "$GID" nginx \
    && adduser --system --disabled-login --ingroup nginx --no-create-home --home /nonexistent --gecos "nginx user" --shell /bin/false --uid "$UID" nginx \
...
```

**Comment by alessfg** [comment]
Heya! I added the feature in the `1.19.5` update https://github.com/nginxinc/docker-nginx-unprivileged/commit/015ce722a117229a49910a394abeb6563e85018e

**Comment by darioseidl** [comment]
Cool, thank you!
