### ISSUE TITLE
mainline-alpine using older alpine

### ISSUE THREAD

**Issue by dinogg** [nginxinc/docker-nginx-unprivileged#58]
A CVE-free `nginxinc/nginx-unprivileged:1.19.6-alpine` released recently (yay!) but it looks like `nginxinc/nginx-unprivileged:mainline-alpine` is still pointing to 1.19.5-alpine.

```
$ docker run -it nginxinc/nginx-unprivileged:mainline-alpine /bin/sh
/ $ more /etc/alpine-release
3.12.1
/ $ nginx -V
nginx version: nginx/1.19.5
built by gcc 9.3.0 (Alpine 9.3.0) 
built with OpenSSL 1.1.1g  21 Apr 2020
...
```

Something similar might have happened back here https://github.com/nginxinc/docker-nginx-unprivileged/issues/20

**Comment by alessfg** [comment]
I think I fixed it. Can you delete the image and re-download it? For some reason manifests sometimes seem to randomly not get pushed/purged correctly and I have no idea why that might be.

**Comment by dinogg** [comment]
It looks good!  Thanks @alessfg!
