### ISSUE TITLE
tagged releases fixed with  version numbers

### ISSUE THREAD

**Issue by stephenmoloney** [nginxinc/docker-nginx-unprivileged#6]
### Issue:

Currently the images in the dockerhub are just divided by type, eg `stable-alpine`
but they are not pinned by version number, eg `alpine-1.14` and `stable-alpine`.

The issue therefore is that `stable-alpine` is a moving target and some users might want access
to a fixed version such as `alpine-1.14`.

### Proposed solution

Release unaltered images with pinned versions

**Comment by alessfg** [comment]
@stephenmoloney I've created new tags as suggested - tags now match the tags for the official NGINX Docker image. You can find a list of the new tags here https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags/.

**Comment by stephenmoloney** [comment]
@alessfg thanks !
