### ISSUE TITLE
weird kubernetes behavior

### ISSUE THREAD

**Issue by fabianbrash** [nginxinc/docker-nginx-unprivileged#60]
Hello,

I used your image to deploy my app a statically generated site using Hugo, everything was working perfectly and then I clicked on the /tags link that Hugo generated, and for some odd reason the port 8080 was appending to the link; I'm using a managed k8s cluster in DigitalOcean, k8s version below and I am using the nginx ingress controller.  I rebuilt my image using the standard nginx-alpine image and everything worked, no issues, I then used an npm-alpine image installed the npm package serve which runs on port 5000 be default, and again everything worked flawlessly.  Do you know of a known issue with your container in k8s when using nginx as the ingress controller?? I looked @ everything I could and nothing referenced 8080 in Hugo, the only reference to it was of course in my deployment YAML's but again that really shouldn't matter, in my Hugo toml file I am using relative pathing "/" so it should just go to fabianbrash.com/tags/ which the link in the browser shows but then I watched as it forwarded to fabianbrash.com:8080/tags/ 

Client Version: v1.20.2
Server Version: v1.19.3
nginx ingress version: nginx-ingress-controller:0.26.1

This is my Dockerfile
````
FROM nginxinc/nginx-unprivileged:1.18-alpine
LABEL maintainer="Fabian Brash"
WORKDIR /usr/share/nginx/html
COPY public/ .

# RUN as non-root
USER 1000
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
````
Thanks,

**Comment by fabianbrash** [comment]
I can duplicate the error in my home lab I'm using the standard nginx ingress controller I'm not making any config changes to it, but when I click on /tags I can see a 301 returned I see it in the nginx ingress logs and in unprivileged nginx logs as well, I'm going to uninstall the nginx ingress controller in my home lab and replace it with another ingress controller(Contour) and I'll see if I get the same results.

**Comment by fabianbrash** [comment]
Confirmed moving to Contour does resolve the issue, I guess it's just a limitation.

**Comment by alessfg** [comment]
If you still want to try to use NGINX at some stage I would recommend posting this issue in our Kubernetes repo (linked in previous comment) too. They'd be better equipped to help you than I am. (Do also note that there's a community NGINX ingress controller and then there's an ingress controller developed by NGINX -- make sure you are using the latter and not the former to get as many features as you can.)

**Comment by fabianbrash** [comment]
Awesome, thanks!

**Comment by fabianbrash** [comment]
even though I closed this I wanted to update, even when I deploy a container using the below command the same thing occurs

````
docker run -d --name fb_com -p 80:5000 7bbc9572cfb9
````

I rebuilt a local version of your image and I am using port 5000 instead of 8080 and if I run

````
docker logs mycontainer
````
I see the below

````
172.17.0.1 - - [05/Feb/2021:14:58:10 +0000] "GET /tags/k8s HTTP/1.1" 301 169 "http://localhost/posts/migration-to-hugo-part1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0" "-"
172.17.0.1 - - [05/Feb/2021:17:52:38 +0000] "GET /tags/ssg HTTP/1.1" 301 169 "http://localhost/posts/migration-to-hugo-part1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0" "-"
172.17.0.1 - - [05/Feb/2021:17:52:41 +0000] "GET /tags/personal HTTP/1.1" 301 169 "http://localhost/posts/migration-to-hugo-part1/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0" "-"
````
Must be some weird Hugo thing...

**Comment by egavrilov** [comment]
Hello,
I just had the same issue and it actually happens with static sites because of missing trailing slash redirection `https://site/url` to `https://site/url/`

The solution is quite simple, just add `absolute_redirect off;` to your server block, e.g.:

```nginx
server {
      listen       8080;
      server_name  _;

      absolute_redirect off;

      root   /usr/share/nginx/html;
      index  index.html index.htm;

      location / {
          try_files $uri $uri/index.html $uri/ =404;
      }
}
```

**Comment by fabianbrash** [comment]
Dude you are a genius when I posted this in the Hugo forums they acted like I was insane.  I will implement this ASAP!! Thanks again!!!
