### ISSUE TITLE
Reboot or docker stop breaks container (exits with 137 code)

### ISSUE THREAD

**Issue by niloct** [nginxinc/docker-nginx-unprivileged#61]
Hi,

I am experiencing a problem with reboots/docker stops on this image.

I have the service configured in a docker_compose file, and it has the `restart: always` in the service configuration.

Nevertheless, if I issue a `docker stop nginx_container` it quits with error 137.

I've seen this recommendation here: https://success.mirantis.com/article/what-causes-a-container-to-exit-with-code-137

My current workaround is, after reboot, issuing a whole `docker compose down` and then `docker compose up`. In this way the container starts successfully.

Any hints on this ? 

Thanks again for the attention.

**Comment by alessfg** [comment]
Hi @niloct -- I cannot seem to replicate your error on my end. I can stop and restart containers just fine. I wonder if the error might be somewhat related to limited user permissions?

**Comment by niloct** [comment]
Well, my docker binary on host is limited to sudo, but then all images but
yours spin up correctly and for stop, exit with 0 code instead of 137.

Em qua, 24 de fev de 2021 09:20, Alessandro Fael Garcia <
notifications@github.com> escreveu:

**Comment by niloct** [comment]
I will try later without deriving from your base image and let you know.
Thanks!

Em qua, 24 de fev de 2021 09:48, Nilo César Teixeira <
nilo.teixeira@gmail.com> escreveu:

**Comment by niloct** [comment]
Indeed the issue was on my end.

I had this script:

```
#! /usr/bin/env sh
set -e
SENHA=$(cat /tmp/senha.txt)
echo $SENHA | sudo -SE shred -u /tmp/senha.txt
echo $SENHA | sudo -SE nginx -g 'daemon off;'
```

in a `/start-nginx.sh`, and that was my `CMD` on my Dockerfile.

What I did was adding the `daemon off;` to nginx configuration, edit sudoers for allowing `nginx` with `nginx-docker ALL = NOPASSWD: /usr/sbin/nginx *`, and edited the `CMD` on Dockerfile to `sudo nginx`.

Then it all worked.

Thanks for your hints again.

**Comment by MarkusGnigler** [comment]
Hi @niloct ,

i know it's a little late, but it could be even simpler with build in docker functions.
Your container with `nginx -g 'deamon: off;'` can't receive no signals anymore. This result's in exit code 137. 
The simplest solution for me, is to exec the foreground process (usually PID1) with `exec` in your script or command instruction in a docker-compose file.

Furder readings:
https://hynek.me/articles/docker-signals/

Regards
Markus
