### ISSUE TITLE
Remove curl and wget from the container.

### ISSUE THREAD

**Issue by hsblhsn** [nginxinc/docker-nginx-unprivileged#63]
Hey there!

`curl` and `wget` is the most common downloader. and they work without privileges. even a blank alpine image does not provide curl and wget by default. So I think you should not too.

Either use a multi staged Dockerfile or remove those extra installed tools just after finishing of their usage.

Thank you!

**Comment by thresheek** [comment]
Hi @hsblhsn, curl is there for a reason: https://github.com/nginxinc/docker-nginx/issues/378

**Comment by alessfg** [comment]
Closing this issue for the time being.
