### ISSUE TITLE
Question : any way to have nodeJS run on this?

### ISSUE THREAD

**Issue by audifaxdev** [nginxinc/docker-nginx-unprivileged#64]
Is there an option to extend this image to include a version of nodeJS / NPM and the ability to run a node process? Sorry if that's just a noob question.

**Comment by alessfg** [comment]
You could use this image as a base image and use something along the lines of `FROM nginxinc:nginx-unprivileged`. You could also use a NodeJS image side by side with this one. There might be other options too. I would suggest reading through the Docker docs or Docker forums 😄
