### ISSUE TITLE
Latest image tags not on DockerHub?

### ISSUE THREAD

**Issue by pentago** [nginxinc/docker-nginx-unprivileged#65]
Is there a reason why latest image tags (e.g. 1.19.8) aren't available on DockerHub, yet there are Dockerfiles present here in repo for a week?

**Comment by alessfg** [comment]
Found the issue. I'm taking the chance to rebuild the images with the latest upstream images -- I'll update this issue once the latest build is up.

**Comment by clakech** [comment]
Hello, We cannot find the 1.19.8 too and there are some CVEs poping that requires an alpine to latest alpine images. Thank you for your work

more info on the fixed CVEs in latest alpine: https://alpinelinux.org/posts/Alpine-3.13.3-released.html

**Comment by mathieu-benoit** [comment]
Apparently only `1.19.8-alpine-amd64` is available to date in there https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags?page=1&ordering=last_updated&name=1.19.8

**Comment by alessfg** [comment]
Yep, as you deduced some tags did get correctly uploaded. That being said, the new builds for `1.19.8` did finally finish and are now live under the right tags. Coming next, `1.19.9`!
