### ISSUE TITLE
Latest image mainline (1.21) not on DockerHub?

### ISSUE THREAD

**Issue by Yoshi-081** [nginxinc/docker-nginx-unprivileged#67]
The latest image tags with mainline (1.21.0) aren't available on DockerHub. Version 1.19.10 is still present.

There Dockerfiles here in the repo are updatet to 1.21.0.

**Comment by alessfg** [comment]
You are right, the build silently failed to push the latest images. Debugging the build process has made me run into the Dockerhub rate limit, so I'll hopefully be able to push the latest manifests throughout tomorrow. For now, you should be able to get the 1.21 images if you specify an arch build (e.g. [nginxinc/nginx-unprivileged:1.21-amd64](https://hub.docker.com/layers/nginxinc/nginx-unprivileged/1.21.0-amd64/images/sha256-897366819e845b043d711859c0eb3e8d38377886caa6e578c974ca3136b23dd9?context=explore))

**Comment by alessfg** [comment]
Should be fixed now 😄
