### ISSUE TITLE
Multiple CVE critical high medium and low errors 

### ISSUE THREAD

**Issue by vish-kp** [nginxinc/docker-nginx-unprivileged#69]
Hi,

We were running twistlock security scans on the docker that only contains nginx unprivileged package and angular files as follows
```
FROM nginxinc/nginx-unprivileged:1.20.1
COPY dist/Template /usr/share/nginx/html
COPY deployment/nginx.conf /etc/nginx/nginx.conf
```
The following errors popped up recently. Would you please address them? Also, please provide us the ETA on when these issues would be resolved.

<img width="826" alt="Screen Shot 2021-06-25 at 10 35 16 AM" src="https://user-images.githubusercontent.com/85310388/123464179-5821e780-d5a1-11eb-8632-07158c554b47.png">

Thanks,
Vish

**Comment by alessfg** [comment]
None of those libraries are used by NGINX so I don't think it's a major issue. I'll rebuild both mainline and stable images once the next NGINX release goes live.

**Comment by dominykas** [comment]
These are all coming from the base Debian image. I doubt there's ever been a time when it had zero vulnerabilities.

You can always `apt update && apt upgrade` to update whatever is updatable.

**Comment by enrico9034** [comment]
Sorry but apt upgrade && apt update does not work if I use your image to base my project, without sudo return Permission Denied and if I add sudo, the error is sudo command not found

**Comment by facco88** [comment]
+1 Same problem with permission denied

**Comment by vish-kp** [comment]
@dominykas apt update && apt upgrade will not work because I do not have the permissions to do it. It doesn't take in sudo command either.

**Comment by enrico9034** [comment]
> @dominykas apt update && apt upgrade will not work because I do not have the permissions to do it. It doesn't take in sudo command either.

You need set user root and after set again user 101 for nginx for example you can add this in your docker fike
``` dockerfile
USER root
RUN apt update && apt -y upgrade
USER 101
```

**Comment by vish-kp** [comment]
That worked, thank you!

**Comment by mteodori** [comment]
Thanks @enrico9034 I did the same on alpine:

```
FROM nginxinc/nginx-unprivileged:1.21.0-alpine
USER root
RUN apk update && apk upgrade
USER 101
```

**Comment by alessfg** [comment]
New images have been built and should be live. From what I gather, almost all of these CVEs should be fixed in the latest upstream Debian buster build, and thus should be fixed in the latest images too. Closing this issue for the time being 😄

**Comment by enrico9034** [comment]
@alessfg Unfortunately, they are not fixed with the Debian or Alpine versions because they are libraries that are installed with the Dockerfile so they must be updated manually, I created a [PR](https://github.com/nginxinc/docker-nginx-unprivileged/pull/71) with the changes to solve this. 
Let us know if it can be merged or if something is not right, please comment on the PR that I will change what you do not like :) :)

**Comment by alessfg** [comment]
Whenever I update the images I rebuild them from scratch, so both the base images as well as the libraries installed should be the latest versions available at build time. That being said, as I've mentioned in other repos over time. This repo is a mirror image of https://github.com/nginxinc/docker-nginx (with a few changes to ensure that the containers run in unprivileged environments). If you'd like to see this change in this repo, I would suggest you first open a PR in the aforementioned repo.

**Comment by sergeyfd** [comment]
@alessfg Thanks! Similar issue is already opened there: https://github.com/nginxinc/docker-nginx/issues/563
