### ISSUE TITLE
Permissions for folders

### ISSUE THREAD

**Issue by stephenmoloney** [nginxinc/docker-nginx-unprivileged#7]
### Question:

apart from `/var/cache/nginx`, should the permissions for the following directories also be changed ?
```
/usr/share/nginx/html/
/var/log/nginx/
```
?

**Comment by KevinWMatthews** [comment]
Isn't the point of this container to run as an unprivileged user? If so, it seems each of these folders should be owned by `nginx`.

I'm not sure which processes write to `/var/cache/nginx`, however. Do you know what would need root permissions?

The standard nginx container should have everything run as and owned by root.

**Comment by alessfg** [comment]
Couple thoughts:
1. `/usr/share/nginx/html` is only used by `nginx` to read files. There is no need to change the permissions of that directory.
2. `/var/log/nginx` is symlinked to `/dev/stdout` and `/dev/stderr` as described on https://docs.docker.com/v17.09/engine/admin/logging/view_container_logs/. From my testing, logs work fine without tweaking any permissions.

**Comment by stephenmoloney** [comment]
1. For `/usr/share/nginx/html` what you say seems right but I ran into some issues on a kubernetes deployment but I need to gather more details. I think there is still an issue here.

2. For the logs, I was getting error logs but not access logs but it must be something in the `.conf` file that was incorrect. 

I'll post more back here after more experimentation/testing later.

**Comment by alessfg** [comment]
> 1. For `/usr/share/nginx/html` what you say seems right but I ran into some issues on a kubernetes deployment but I need to gather more details. I think there is still an issue here.

Please do! Further details would definitely help 😄 

> 2\. For the logs, I was getting error logs but not access logs but it could be something in the custom `.conf` file that I wrote was incorrect.

In my testing I did get access logs, and any logs written to `/var/log/nginx` should be appropriately symlinked. As you mentioned, I'd me more inclined to think that there may have been some issues with your `.conf` file.
