### ISSUE TITLE
Update base Alpine image

### ISSUE THREAD

**Issue by sergeyfd** [nginxinc/docker-nginx-unprivileged#72]
Can this https://github.com/nginxinc/docker-nginx/pull/556/files be applied here?

**Comment by alessfg** [comment]
It already is? https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/mainline/alpine/Dockerfile

**Comment by sergeyfd** [comment]
I still see 3.13 there https://github.com/nginxinc/docker-nginx-unprivileged/blob/043153745312e4a45b9e6db7e65bed2ab1f3681e/stable/alpine/Dockerfile#L6

**Comment by alessfg** [comment]
Stable is at 3.13 per the official upstream images. Check https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L6.
