### ISSUE TITLE
Latest patch updates

### ISSUE THREAD

**Issue by bendem** [nginxinc/docker-nginx-unprivileged#75]
Hi, it looks like this is an official-ish nginx image, maintained by the nginx team. Any reason why it's not being updated at the same rate as the [official privileged images](https://github.com/nginxinc/docker-nginx/commits/master)?

**Comment by alessfg** [comment]
Long story short, there's usually a lag of about a week between the former and these ones. The latest unprivileged images are being built at the moment and should hopefully be live before end of week.

**Comment by alessfg** [comment]
New images are live!
