### ISSUE TITLE
Ensure NGINX directories and files are owned by root

### ISSUE THREAD

**Issue by alwibrm** [nginxinc/docker-nginx-unprivileged#79]
According to the hardening guidelines of [NGINX CIS Benchmark](https://www.cisecurity.org/benchmark/nginx/) chapter 2.3.1 "_Ensure NGINX directories and files are owned by root (Scored)_" the folder `/etc/nginx` and its files should be owned by root. However in line 127 of the Alpine Dockerfile of this project the owner is set to `nginx`:
https://github.com/nginxinc/docker-nginx-unprivileged/blob/04106e64d1fa66616ce3b1f24395515d691b4a57/stable/alpine/Dockerfile#L127

**Comment by alessfg** [comment]
This is done to ensure the images run in OpenShift.

**Comment by alwibrm** [comment]
Thanks for the quick reply, @alessfg. Do you see any possibility to set the owner to root for other platforms than OpenShift?

**Comment by alessfg** [comment]
To be honest, I don't think so? Besides running in OpenShift these images are meant to be run in environments where the user does not have access to root privileges. Have you checked the official Docker NGINX image?

**Comment by alwibrm** [comment]
The NGINX CIS Benchmark further states NGINX should be run as a "_non-privileged, dedicated service account_" (see chapter 2.2.1 of the hardening guideline linked in the description of this issue). That was the reason for us to use nginx-unprivileged instead of the official Docker NGINX image.

**Comment by alessfg** [comment]
If you check the official Docker NGINX image, you'll see that the worker processes are run as the `nginx` user. And the `nginx` user does indeed not have privileged rights.
```
root@ed3b637187c5:/# sudo -l -U nginx
User nginx is not allowed to run sudo on ed3b637187c5.
```
That meets the CIS Benchmark 2.2.1 audit criteria.

**Comment by alwibrm** [comment]
Thank you for pointing that out, @alessfg. You're right.
