### ISSUE TITLE
Tolerate existing user/group.

### ISSUE THREAD

**Issue by libesz** [nginxinc/docker-nginx-unprivileged#80]
Hey!
I am about to use nouser:nogroup (65534:65534) with `--build-arg` to build/run my unprivileged nginx. My system has certain constraints so this is the only user that suits my need. As this user usually exists in the base images already, the build fails now:
```
+ addgroup -g 65534 -S nginx
addgroup: gid '65534' in use
```

I did a quick fix for the build to tolerate/allow the usage of existing users in Dockerfile:
```
 && addgroup -g $GID -S nginx || true \
 && adduser -S -D -H -u $UID -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx || true \
```

I think it could be a useful feature for others as well, maybe in a more elegant way 😄 .

**Comment by alessfg** [comment]
I think I agree that this could actually be a useful feature in some environments like the one you mentioned. The overall experience when running this image in an unprivileged environment should be as frictionless as possible, and your suggestion would help in that regard.

Let me do some research and play with this on my end and get back to you. (In the meantime, feel free to create a PR too!)

**Comment by alessfg** [comment]
Alright after playing a little bit with this I think it is an overall good add. Whenever a new version of these images gets built I'll add the change and if everything goes well, will push the change.

**Comment by libesz** [comment]
Thank you @alessfg for the support! 🥳
