### ISSUE TITLE
Issue: nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)

### ISSUE THREAD

**Issue by MuhammadMunir12** [nginxinc/docker-nginx-unprivileged#81]
I am trying to run nginx on openshift but facing this directory permisisons issues. Due to this error container is not creating. 
The following permissions are set to files created manually. 
```
drwxr-xr-x.  3 root root   79 Dec 22 02:50 /etc/nginx
drwxr-xr-x.  2 root root   26 Dec 22 02:50 /etc/nginx/conf.d
-rw-r--r--.  1 root root 5231 Dec 22 02:48 /etc/nginx/mime.types
drwxrwxr-x.  3 root root   25 Dec 22 01:23 /var/cache/nginx
drwxrwxr-x.  2 root root    6 Dec 22 01:10 /var/log/nginx
drwxrwxr-x. 47 root root 1340 Dec 21 06:51 /var/run

```

Any help would be appreciated.

**Comment by alessfg** [comment]
It's hard to debug what's going without more info. What docker command are you using to run the image? Are you copying any new files? Is user 101 already in use by another OpenShift cluster?

**Comment by Majid-cloud** [comment]
The problem is resolved by changing nginx image.

**Comment by MuhammadMunir12** [comment]
Hi, 
The issue was in nginx image, changing the nginx version resolved the issue.

**Comment by hasnain2808** [comment]
@MuhammadMunir12 
what version did you switch it to?
