### ISSUE TITLE
1.21.5 is out

### ISSUE THREAD

**Issue by steenzout** [nginxinc/docker-nginx-unprivileged#82]
Would it be possible to update this repo to use the latest nginx release, please?

https://nginx.org/en/CHANGES

Thank you!

**Comment by DevDavido** [comment]
Is there maybe a way to keep both repos ([normal](https://github.com/nginxinc/docker-nginx) and [unprivileged](https://github.com/nginxinc/docker-nginx-unprivileged)) in sync version-wise? Maybe with [dependabot](https://github.com/dependabot)?

**Comment by alessfg** [comment]
Heya! There's some issues on the backend that might delay the unprivileged 1.21.5 image being built and released but rest assured I have not forgotten!

Re using dependabot or a similar tool, you'll have to bring that up in the main upstream repository. My gut feeling says that that it's not likely, but feel free to open an issue!

**Comment by alessfg** [comment]
Brief update -- 1.21.5 images should be live within the next couple days. Aiming for early next week for 1.21.6 images.

**Comment by alessfg** [comment]
Aaand forgot to update this, but 1.21.6 images are out now too! 😄

**Comment by steenzout** [comment]
> Aaand forgot to update this, but 1.21.6 images are out now too! 😄

thank you for your work on this!
