### ISSUE TITLE
Issue when trying to run a shell script

### ISSUE THREAD

**Issue by robbo10** [nginxinc/docker-nginx-unprivileged#83]
Hi there,

During the docker build phase I'm coping over a bash script, this script just reads env variables, I also have to change the script to be an executable during build I get the following error

```
 > [stage-1 3/4] RUN chmod +x /usr/share/nginx/html/env.sh:
#16 0.212 chmod: /usr/share/nginx/html/env.sh: Operation not permitted
```

**Comment by alessfg** [comment]
If you are extending this Docker image, `chmod` might get executed by the unprivileged user created in the Dockerfile, and as such it wouldn't have the necessary permissions to make your script executable. Assuming that's what you are doing, can you try cloning the Dockerfiles in this repo and adding your tweaks before the Docker `USER` gets set?

**Comment by robbo10** [comment]
I did try setting `USER root` and changing the `/usr/share/nginx/html` directory to `nginx:nginx` as this is where the executable is getting copied.  I was then able to run the `chmod` command before setting the user back to be `nginx`.  However within kubernetes when trying to start the container, it tries to run that executable which then throws another permissions error.

Is this possible ? :)

**Comment by alessfg** [comment]
Sadly there's a few different reason why that might be happening and I don't know that I am the best person to help you debug kubernetes.  My only further suggestion is to make sure that the files are executable by the `nginx` user (eg use `chown` in addition to `chmod` -- check the Dockerfiles [here](https://github.com/nginxinc/docker-nginx-unprivileged/blob/main/Dockerfile-debian.template#L103-L107) for an example).
