### ISSUE TITLE
libxml2 vulnerability

### ISSUE THREAD

**Issue by rgarcia89** [nginxinc/docker-nginx-unprivileged#84]
I am getting the following vulnerability in image `nginxinc/nginx-unprivileged:1.21.4-alpine`
![image](https://user-images.githubusercontent.com/4134730/158391209-1524707a-1490-4368-b11c-d73eb3ddb214.png)

Could you please update the libxml2 package?
It is already available: https://alpine.pkgs.org/3.12/alpine-main-x86_64/libxml2-2.9.13-r0.apk.html

**Comment by rgarcia89** [comment]
@alessfg same counts for v1.21.6-alpine
![image](https://user-images.githubusercontent.com/4134730/158427818-3524e306-cb43-46d8-ba8d-afc79e689208.png)

**Comment by alessfg** [comment]
Aight, I'll make a note to rebuild the images asap. That being said, NGINX does not depend on that library so as long as you only use the image for NGINX you should be good to go.

**Comment by alessfg** [comment]
New images are up!
