### ISSUE TITLE
Alpine Linux version in Docker image tag

### ISSUE THREAD

**Issue by rokf** [nginxinc/docker-nginx-unprivileged#87]
### Is your feature request related to a problem?

The Docker image tag doesn't say which version of Alpine Linux was used. One has to exec into a running container to see which Alpine Linux version it's running. We're having problems tracking CVE because of that.

### Describe the solution you'd like

Additional tag(s) would be added which would include the Alpine Linux version in the tag's name, ideally including the patch number. This way we'd be able to choose the Alpine Linux version through the Docker image tag when it'd be present (built).

I understand that the patch number would have to be pulled dynamically from somewhere as part of the GitHub Actions pipeline.

### Describe alternatives you've considered

We continue checking the Alpine Linux versions manually when fresh Docker images are pulled. We disable Docker image caching.

**Comment by alessfg** [comment]
For the most part every `mainline` image is built on the latest version of Alpine Linux (the stable image varies between the latest and previous to latest version). My usual suggestion with feature requests such as this is to try to get the feature implemented in the upstream Docker NGINX repo first, and then I'll port it over here. I will say that this seems like a reasonable ask altogether so I think we can get it implemented.

**Comment by rokf** [comment]
Alright. You're proposing that I open a similar issue on https://github.com/nginxinc/docker-nginx and get back here once that is resolved?

**Comment by rokf** [comment]
Issue has been opened - https://github.com/nginxinc/docker-nginx/issues/649

**Comment by alessfg** [comment]
Per the conversation on https://github.com/nginxinc/docker-nginx/issues/649 it seems as if there is no easy way to add the patch version into the tags without potentially messing the existing Docker build pipeline. I'm closing this issue for the time being but if things change in the future, I am more than happy to reopen it 😄
