### ISSUE TITLE
Unprivileged container should not be run as root

### ISSUE THREAD

**Issue by KevinWMatthews** [nginxinc/docker-nginx-unprivileged#9]
Any word on pull request #8 ? I'm curious to hear your feedback on this issue.

Also see a new question on #5 .

**Comment by alessfg** [comment]
Sorry about the delay responding to the PR. I somehow missed the PR notification!

**Comment by KevinWMatthews** [comment]
No problem. Life takes time, but I didn't want this one to slip through the cracks.

Thanks for closing. The PR has a better description.
